### ISSUE TITLE
Searching account custom data

### ISSUE THREAD

**Issue by dpwoodford** [stormpath/stormpath-sdk-python#327] opened 2017-01-15 08:27 UTC
Has the ability to search account custom data been built into the Python SDK yet? I see it's available for searching groups..

accounts = application.accounts.search('customData.foo=fred') seems like it should return a list of accounts in the same way as application.accounts.search(username) as far as I can tell, but I get a 0 length list in response..

**Comment by dpwoodford** [comment] 2017-01-15 10:55
Just to follow up on this; I see you can search at the directory level, but I'm still getting inconsistent returns between the SDK and the REST API.

If customData.iamalist = ['hello','world'], then the REST API endpoint:
` accounts?customData.iamalist=world` 
returns the account, but 
`maindir.accounts.search({'customData.iamalist':'world'}) `
doesn't seem to..

Am I missing something on how to formulate the request?

**Comment by dinkom** [comment] 2017-01-20 15:12
Hey @dpwoodford, which version of the stormpath package are you using? I have tried with 2.4.5 and the latest, 2.5.1 and these are my results:

```application = client.applications.search({'name': 'my-app-name'})[0]
maindir = client.directories[0]` (default dir)
acc = maindir.accounts.create({'email': 'some@email.com', 'password': 'Some!Pass1'})
acc.custom_data.iamalist = ['hello', 'world']
acc.save()

# re-run the program, without creating the user again

# 1st iterration works
acc = dr.accounts.search({'customData.iamalist': 'world'})[0]
print acc.custom_data.iamalist
[u'hello', u'world']

# 2nd iterration works
acc = dr.accounts.search({'customData.iamalist': '[world]'})[0]
print acc.custom_data.iamalist
[u'hello', u'world']

# 3rd iterration works
acc = dr.accounts.search({'customData.iamalist': '["world"]'})[0]
print acc.custom_data.iamalist
[u'hello', u'world']

# 4th iterration
acc = dr.accounts.search({'customData.iamalist': '[hello, world]'})[0]
print acc.custom_data.iamalist
[u'hello', u'world']

# 5th iterration does not work
acc = dr.accounts.search({'customData.iamalist': '["hello", "world"]'})[0]
print acc.custom_data.iamalist
IndexError: list index out of range```

**Comment by rdegges** [comment] 2017-01-26 17:49
Going to close this for now as we cannot reproduce.

**Closed by rdegges** 2017-01-26 17:49 UTC
