### ISSUE TITLE
stormpath increases app response time 10x

### ISSUE THREAD

**Issue by ohadperry** [stormpath/stormpath-sdk-python#264] opened 2016-05-24 12:48 UTC
@rdegges @senko please help
storpmath version `2.3.1`
started using `stormpath` as my authenticating service:
using python's Flask. 
in order to authenticate , the user sends an access token in the request's header 

```
 headers = {
    'Authorization': 'Bearer <token_id>'
 }
```

my way of validating is :

```

authenticator = ApiRequestAuthenticator(application)
uri = 'bla_dont_care.com'
result = authenticator.authenticate(headers=request.headers, http_method='GET', uri=uri, body={}, scopes=[])
is_valid = result.account is not None
```

the authenticator is not being initiated in every request but saved in the memory . 

My response time raised from `40ms` to `450ms` !!
This is, ofcourse, a show stopper. 
I read that stormpath sdk[ caches the api calls](http://flask-stormpath.readthedocs.io/en/latest/product.html#enable-caching) specifically for this. 

Trying to debug this , I did see that the cache get 2 misses per 1 request here
https://github.com/stormpath/stormpath-sdk-python/blob/master/stormpath/cache/cache.py#L46

The key it failes to find is 

```
https://api.stormpath.com/v1/applications/VJiXDWTWnYdNgrFe9BoI3/accounts/6TGIMWF47DO0XUK96M07XEMG1
```

Trying to debug this further I saw that that resource is not found that is FAILS to find the resource here
https://github.com/stormpath/stormpath-sdk-python/blob/master/stormpath/data_store.py#L139

my questions are what account is he looking for ? `6TGIMWF47DO0XUK96M07XEMG1` is not the account sent ?

The `6TGIMWF47DO0XUK96M07XEMG1` is coming from the token 
https://github.com/stormpath/stormpath-sdk-python/blob/master/stormpath/api_auth.py#L97
but the token sent is getting from 

```
    def get_client_access_token(self, app, user_data):
        api_key = self.get_api_key(app, user_data)

        uri = 'bla_dont_care.com?grant_type=client_credentials'
        http_method = 'GET'
        headers = {
            'Authorization': 'Basic ' + base64.b64encode(api_key.id + ":" + api_key.secret)
        }
        result = self.authenticator.authenticate(headers=headers, http_method=http_method, uri=uri, body={}, scopes=[])
        if result:
            client_token = result.token.token
        else:
            raise Exception('Invalid or not authenticated request.')


    def get_api_key(self, app, user_data):

        self.init_authenticator()

        email = user_data['email']
        if not hasattr(self, 'cloud_directory'):
            self.cloud_directory = app.stormpath_helper.get_cloud_directory(APP_NAME + '-' +  env)

        if self.accounts.get(email) is None:
            account = self.cloud_directory.accounts.search({'email': email})
            if account is None:
                raise Exception('failed to find account')

            self.accounts[email] = account[0]

        if self.api_keys.get(email) is None:
            api_key = self.accounts[email].api_keys.create()
            self.api_keys[email] = api_key

        return self.api_keys[email]

```

any way else I can debug this ?

**Comment by ohadpartuck** [comment] 2016-05-24 13:51
also tried this
```
authenticator = JwtAuthenticator(application)
jwt_authentication_result = authenticator.authenticate(oauth_grant_authentication_result.access_token.token)
```

same time - 450ms

**Comment by ohadpartuck** [comment] 2016-05-24 14:37
getting weird keys for cahce:
```
key = 'https://api.stormpath.com/v1/apiKeys/https://api.stormpath.com/v1/accounts/1kgApqcUsOcyHYljRdLqRT'
```
do they make sense?

**Comment by senko** [comment] 2016-05-25 08:23
Hey @ohadpartuck — looks like an faulty interference between api keys and jwt generation. From what I was able to trace:

* when you exchange Basic-auth API key for JWT key (with grant_credentials), you get a JWT that has the API key as a `sub` field in JWT
* when the Stormpath SDK creates the JWT keys, it uses the account href as a `sub` field in JWT
* the access token validation mechanism checks to see if the JWT sub refers to the account (by issuing a request to the stormpath server), and when it fails, it fallbacks to checking the API key
* failed 404 requests (resource not found) are not cached

All this combined, means that you get several attempts at retrieving the account while the identifier in question is actually the API key, and those are spurious accounts you noticed.

If the JWT is generated locally (carrying the account href) and then treated as if it carries API key, cache keys like the above would be generated.

I think the solution to this would be to check whether the sub field looks like a href (easily done by checking whether its prefix is the stormpath api base url), and treat it as either account href or api key, but not both.

@rdegges thoughts?

**Comment by ohadpartuck** [comment] 2016-05-25 14:56
hi @senko , thanks for the response. 
when you say the solution is to " sub field looks like a href " , what exactly do you mean? where should I look exactly ? and what output should I return ?

**Comment by rdegges** [comment] 2017-01-10 17:46
Hey guys, sorry for the delay. We're finally getting around to work on this. We're doing some reproducing with the latest release of this library. Will update the ticket when we get some more infos!

**Comment by dinkom** [comment] 2017-01-13 09:28
We've done some experimenting and we were not able to reproduce this behaviour. After the authentication, accessing `result.account` did not make any calls to the API, it just read the account from memory and the time it took to do it was negligible. Could be that the possible issue was resolved in the new versions of Stormpath.

**Comment by rdegges** [comment] 2017-01-13 17:55
Closing for now, thanks @dinkom!

**Closed by rdegges** 2017-01-13 17:55 UTC
