### ISSUE TITLE
custom_data always uses NoCache()

### ISSUE THREAD

**Issue by stauffec** [stormpath/stormpath-sdk-python#113] opened 2015-01-23 13:11 UTC
I'm not sure if this is by design, but it appears to me that caching does not occur for custom_data. Is that by design? The following code reference shows that the NoCache class will be selected every time the url for custom_data is passed in. Look at the line: "parts[-2] in self.CACHE_REGIONS". For custom_data urls, the parts[-2] points to the actual object id ( e.g /v1/accounts/wff2f23f2f322/custom_data). Because it incorrectly fails to grab the actual 'accounts' parts, it then skips any caching. Is this intentional? I'm not even sure if the python sdks supports link expansion, but perhaps that should be used here?

    def _get_cache(self, href):
        class NoCache(object):
            def get(self, *args, **kwargs):
                return None

            def put(self, *args, **kwargs):
                pass

            def delete(self, *args, **kwargs):
                pass

        if '/' not in href:
            return NoCache()

        parts = href.split('/')
        if parts[-2] in self.CACHE_REGIONS:  # We only care about instances.
            return self.cache_manager.get_cache(parts[-2]) or NoCache()
        else:
            return NoCache()

**Comment by stauffec** [comment] 2015-01-23 20:51
One additional test. I tried using the expand functionality, and interestingly enough, the object returned from client.accounts.get(URL,expand) does return an object that includes the customData (no additional http request), however, if the subsequent calls are made again to client.accounts.get(URL), the cached version definitely loses that customData and thus triggers another http call. Unless I'm missing something this appears to severely limit the benefit from using caching.

**Comment by rdegges** [comment] 2015-01-23 22:26
Thanks for the info!

@denibertovic would you take a look at this one?

**Comment by denibertovic** [comment] 2015-01-26 12:37
I'm 99% certain this is by design. But will look into it.

**Comment by rdegges** [comment] 2015-01-26 18:33
@denibertovic I'm pretty certain we want this if it isn't there atm.

For a lot of users, they'll be making lots of custom data requests, so having it cached is pretty important for minimizing latency.

**Comment by stauffec** [comment] 2015-01-26 18:42
Right now my only option is to either cache it myself or dump it in an unused field like 'middle name'. Both poor options. This seems like an MVP type feature.

**Comment by denibertovic** [comment] 2015-01-26 18:47
@rdegges @stauffec I 100% agree that we need this! I'm just trying to figure out what were the historical problems with this and why it was left out in the initial implementation so we know the right way to attack the problem.

**Comment by rdegges** [comment] 2015-01-26 18:49
Totally! No pressure ^^

**Comment by rdegges** [comment] 2015-01-28 17:49
This just got merged in, I'm cutting a release now. Look for 1.3.2 on PyPI in the next hour =)

**Closed by rdegges** 2015-01-28 17:49 UTC
